# Generated by Django 4.2.5 on 2023-09-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('date_of_delivery', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
