# Generated by Django 4.2.5 on 2023-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientdetails_date_added_clientdetails_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('to_number', models.CharField(max_length=15)),
                ('sid', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
