# Generated by Django 4.2.5 on 2023-10-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clientdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='value',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='contact',
            field=models.IntegerField(default=712345678, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='id_number',
            field=models.IntegerField(default=37160450, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='wa_number',
            field=models.IntegerField(default=712345678, max_length=15),
            preserve_default=False,
        ),
    ]
